export const INDIA_HIGH_POTENTIAL_CITIES = [
  'Udaipur',
  'Goa North',
  'Goa South',
  'Manali',
  'Kasol',
  'Rishikesh',
  'Dharamshala',
  'Bir',
  'Spiti Valley',
  'Leh',
  'Mussoorie',
  'Nainital',
  'Jaipur',
  'Jaisalmer',
  'Jodhpur',
  'Pushkar',
  'Gokarna',
  'Hampi',
  'Pondicherry',
  'Varkala',
  'Munnar',
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Pune',
  'Hyderabad',
  'Coorg',
  'Wayanad',
  'Alleppey',
  'Kodaikanal',
  'Ooty',
  'Tirthan Valley',
  'Ziro',
  'Varanasi',
  'Haridwar',
  'Amritsar',
  'Indore',
  'Bhopal',
  'Chandigarh',
  'Surat',
  'Ahmedabad',
] as const

export const DEFAULT_LAUNCH_CITY = 'Udaipur'
